with open('automate_login.py', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update classify_and_extract dealer_name assignment for is_invoice
target_dealer = '            dealer_name = openai_res.get("company_name")'
replacement_dealer = '            dealer_name = openai_res.get("dealership_name") or openai_res.get("company_name")'

if target_dealer in content:
    content = content.replace(target_dealer, replacement_dealer)
    print("Updated dealer_name extraction logic for is_invoice")
else:
    print("Target dealer name block not found in automate_login.py")

# 2. Update classify_and_extract vehicle_make assignment for is_disclaimer
target_make = '            vehicle_make = openai_res.get("company_name")'
replacement_make = '            vehicle_make = openai_res.get("dealership_name") or openai_res.get("company_name")'

if target_make in content:
    content = content.replace(target_make, replacement_make)
    print("Updated vehicle_make extraction logic for is_disclaimer")
else:
    print("Target vehicle make block not found in automate_login.py")

# 3. Update verify_document_with_openai_and_portal prompt rules for authorized signature
target_prompt = """### Authorized Signature Validation
* Locate the dealer/company/authorized signatory section (usually at the bottom or corner of the invoice).
* Determine whether an authorized signature is present. This can be EITHER:
  1. A handwritten signature/scribble (in blue, black, or other ink), which is very commonly found overlapping or inside the dealer stamp/seal.
  2. A digital signature block (e.g., "Digitally Signed by...", "Signed by...").
* IMPORTANT: Do NOT mark the authorized signature as missing just because you see the text "Signature Not Verified". "Signature Not Verified" is a technical warning generated by PDF viewers, but the digital signature text block itself is present and counts as a valid digital signature.
* If you see any blue/black ink handwritten signature/scribble inside or near the round/rectangular dealer stamp, that counts as a valid authorized signature.
* If either a digital signature block or a handwritten signature/scribble is present in the authorized signatory section, mark "present: true"."""

replacement_prompt = """### Authorized Signature Validation
* Locate the dealer/company/authorized signatory section (usually at the bottom or corner of the invoice).
* Determine whether an authorized signature is present. This can be EITHER:
  1. A handwritten signature/scribble (in blue, black, or other ink), which is very commonly found overlapping or inside the dealer stamp/seal.
  2. A digital signature block (e.g., "Digitally Signed by...", "Signed by...").
  3. A handwritten initials, employee code (like "SKR/103571"), or name written inside the stamp/seal by the dealer representative, which functions as their signature.
* IMPORTANT: Do NOT mark the authorized signature as missing just because you see the text "Signature Not Verified". "Signature Not Verified" is a technical warning generated by PDF viewers, but the digital signature text block itself is present and counts as a valid digital signature.
* IMPORTANT: Do NOT mark the authorized signature as missing if there is any handwritten scribble, initials, or code written in blue/black ink inside or overlapping the dealer stamp/seal. Even if it looks like simple initials or numbers, if it is written by hand (not printed as part of the page text) inside the stamp, it counts as a valid authorized signature.
* If either a digital signature block, a handwritten scribble/signature, or handwritten initials/code inside the stamp is present, mark "present: true"."""

if target_prompt in content:
    content = content.replace(target_prompt, replacement_prompt)
    print("Updated authorized signature prompt rules")
else:
    # Try alternate target prompt block in case whitespace is slightly different
    # We will do a generic replacement using regex or split
    print("Target prompt block not found - using partial search")
    content = content.replace(
        '  2. A digital signature block (e.g., "Digitally Signed by...", "Signed by...").',
        '  2. A digital signature block (e.g., "Digitally Signed by...", "Signed by...").\n  3. A handwritten initials, employee code (like "SKR/103571"), or name written inside the stamp/seal by the dealer representative, which functions as their signature.'
    )
    content = content.replace(
        '* If you see any blue/black ink handwritten signature/scribble inside or near the round/rectangular dealer stamp, that counts as a valid authorized signature.',
        '* IMPORTANT: Do NOT mark the authorized signature as missing if there is any handwritten scribble, initials, or code written in blue/black ink inside or overlapping the dealer stamp/seal. Even if it looks like simple initials or numbers, if it is written by hand (not printed as part of the page text) inside the stamp, it counts as a valid authorized signature.\n* If you see any blue/black ink handwritten signature/scribble inside or near the round/rectangular dealer stamp, that counts as a valid authorized signature.'
    )
    content = content.replace(
        '* If either a digital signature block or a handwritten signature/scribble is present in the authorized signatory section, mark "present: true".',
        '* If either a digital signature block, a handwritten scribble/signature, or handwritten initials/code inside the stamp is present, mark "present: true".'
    )
    print("Partial search replacements done")

with open('automate_login.py', 'w', encoding='utf-8') as f:
    f.write(content)
print("Save complete")
