with open('automate_login.py', 'r', encoding='utf-8') as f:
    content = f.read()

target = """### Authorized Signature Validation
* Locate the dealer/company/authorized signatory section (usually at the bottom or corner of the invoice).
* Determine whether a genuine handwritten authorized signature is present.
* The signature may overlap with a company stamp.
* If no handwritten signature is visible in the authorized/dealer section, mark it as missing."""

replacement = """### Authorized Signature Validation
* Locate the dealer/company/authorized signatory section (usually at the bottom or corner of the invoice).
* Determine whether an authorized signature is present. This can be EITHER:
  1. A handwritten signature/scribble (in blue, black, or other ink), which is very commonly found overlapping or inside the dealer stamp/seal.
  2. A digital signature block (e.g., "Digitally Signed by...", "Signed by...").
* IMPORTANT: Do NOT mark the authorized signature as missing just because you see the text "Signature Not Verified". "Signature Not Verified" is a technical warning generated by PDF viewers, but the digital signature text block itself is present and counts as a valid digital signature.
* If you see any blue/black ink handwritten signature/scribble inside or near the round/rectangular dealer stamp, that counts as a valid authorized signature.
* If either a digital signature block or a handwritten signature/scribble is present in the authorized signatory section, mark "present: true"."""

target_rules = """Determine the presence of:
* Customer Signature (handwritten signature in customer signature area)
* Authorized Signature (handwritten signature in dealer/authorized section)
* Company Stamp (visible stamp/seal impression)"""

replacement_rules = """Determine the presence of:
* Customer Signature (handwritten signature in customer signature area)
* Authorized Signature (handwritten or digital signature in dealer/authorized section)
* Company Stamp (visible stamp/seal impression)"""

if target in content:
    content = content.replace(target, replacement)
    content = content.replace(target_rules, replacement_rules)
    with open('automate_login.py', 'w', encoding='utf-8') as f:
        f.write(content)
    print("Successfully updated authorized signature prompt rules")
else:
    print("Target block not found in automate_login.py")
